# Generated by Django 5.2.8 on 2025-12-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_request', '0005_remove_translationrequest_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
