# Generated by Django 5.2.8 on 2025-12-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_request', '0006_alter_translationrequest_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='duration_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
