# Generated by Django 5.2.9 on 2025-12-06 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_request'),
        ('translation_request', '0009_translationrequest_company_translationrequest_status_and_more'),
        ('translators', '0012_specialty_remove_translator_specialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('transferred', 'Transferred to Translator')], default='issued', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('company_payment_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='translation_request.translationrequest')),
                ('translator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_received', to='translators.translator')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
