# Generated by Django 5.2.7 on 2025-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('translator', 'Translator'), ('company', 'Company'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
