# Generated by Django 5.2.7 on 2025-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0008_remove_translator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
