# Generated by Django 5.2.7 on 2025-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0009_translator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
